
import { AnalysisVariable } from "../VariableControl";

// Sample data for our analysis
export const sampleVariables: AnalysisVariable[] = [
  {
    id: "1",
    name: "Labor Cost",
    baseValue: 250000,
    minValue: 200000,
    maxValue: 300000,
    impact: -27500,
    category: "Cost",
    metric: "cost",
  },
  {
    id: "2",
    name: "Materials",
    baseValue: 150000,
    minValue: 120000,
    maxValue: 180000,
    impact: -15000,
    category: "Cost",
    metric: "cost",
  },
  {
    id: "3",
    name: "Project Duration",
    baseValue: 180,
    minValue: 160,
    maxValue: 200,
    impact: -12500,
    category: "Schedule",
    metric: "cost",
  },
  {
    id: "4",
    name: "Revenue Growth",
    baseValue: 500000,
    minValue: 450000,
    maxValue: 600000,
    impact: 45000,
    category: "Revenue",
    metric: "cost",
  },
  {
    id: "5",
    name: "Market Penetration",
    baseValue: 15,
    minValue: 10,
    maxValue: 20,
    impact: 30000,
    category: "Market",
    metric: "cost",
  },
  {
    id: "6",
    name: "Customer Acquisition",
    baseValue: 2000,
    minValue: 1500,
    maxValue: 2500,
    impact: -8500,
    category: "Marketing",
    metric: "cost",
  },
  {
    id: "7",
    name: "Equipment Efficiency",
    baseValue: 85,
    minValue: 75,
    maxValue: 95,
    impact: 17500,
    category: "Operations",
    metric: "performance",
  },
  {
    id: "8",
    name: "Quality Control",
    baseValue: 92,
    minValue: 85,
    maxValue: 98,
    impact: 9500,
    category: "Quality",
    metric: "performance",
  },
  {
    id: "9",
    name: "Resource Allocation",
    baseValue: 150000,
    minValue: 130000,
    maxValue: 170000,
    impact: -11000,
    category: "Resources",
    metric: "schedule",
  },
  {
    id: "10",
    name: "Technology Implementation",
    baseValue: 200000,
    minValue: 180000,
    maxValue: 220000,
    impact: 22000,
    category: "Technology",
    metric: "performance",
  },
  {
    id: "11",
    name: "Supply Chain Delays",
    baseValue: 15,
    minValue: 5,
    maxValue: 25,
    impact: -19500,
    category: "Supply Chain",
    metric: "schedule",
  },
  {
    id: "12",
    name: "Staff Productivity",
    baseValue: 75,
    minValue: 65,
    maxValue: 85,
    impact: 14500,
    category: "Operations",
    metric: "performance",
  }
];

export const metrics = ["Cost", "Schedule", "Performance"];
